GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users/id_user
###
POST http://localhost:3000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "   ",
    "username" : "",
    "email" : ""
}

###
POST http://localhost:3000/api/users/id_company HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "username" : "",
    "email" : ""
}

###
PUT http://localhost:3000/api/users/id_user HTTP/1.1
Content-Type: application/json

{
   "username" : ""
}

###
DELETE  http://localhost:3000/api/users/id_user
###





GET http://localhost:3000/api/companies
###

GET http://localhost:3000/api/companies/id_company
###

GET http://localhost:3000/api/id_company/companies
###

POST http://localhost:3000/api/companies/ HTTP/1.1
Content-Type: application/json

{
    "name": ""
}

###
PUT http://localhost:3000/api/companies/id_company HTTP/1.1
Content-Type: application/json

{
   "name" : 
}
###

DELETE  http://localhost:3000/api/companies/id_company
###


